name: Prettier CI

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '-nopretty')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettier CI
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,jsx,ts,tsx}
          commit_message: "Made the code prettier! 🔨"
